In [1]:
import numpy as np

In [7]:
#zeros(shape,dtype=float/jiska chye uska ,order='c')
data = np.zeros((3,3),dtype =int)
print(data)
print(data.ndim)
data1 = np.zeros((3,3,2),dtype =int)
print(data1)
print(data1.ndim)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
2
[[[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]

 [[0 0]
  [0 0]
  [0 0]]]
3


In [9]:
#ones(shape,dtype=float/jo chye wo)
data = np.ones((3,2),dtype=int)
print(data)

[[1 1]
 [1 1]
 [1 1]]


In [11]:
data = np.ones((2),dtype=int)
print(data)
data = np.ones((0),dtype=int)
print(data)
print(data.ndim)
data = np.ones((0,0),dtype=int)
print(data)
print(data.ndim)

[1 1]
[]
1
[]
2


In [12]:
data = np.empty((2,2))
print(data)

[[6.23042070e-307 4.67296746e-307]
 [1.69121096e-306 3.11521375e-307]]


In [19]:
arr = np.full((3,3),np.pi)
print(arr)

[[3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265]]


In [15]:
arr = np.full((3,3),'Hello',dtype='U5')# U defines how maany characters of string you want
print(arr)

[['Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello']
 ['Hello' 'Hello' 'Hello']]


In [16]:
arr = np.full((3,3),'Hello',dtype='U3')
print(arr)

[['Hel' 'Hel' 'Hel']
 ['Hel' 'Hel' 'Hel']
 ['Hel' 'Hel' 'Hel']]


In [20]:
data = np.identity(4 , dtype=int)
print(data)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [33]:
arr = np.arange(12)
re_arr = np.reshape(arr,(2,6),order="F")
print(arr)
print(re_arr)
print(re_arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  2  4  6  8 10]
 [ 1  3  5  7  9 11]]
2


In [32]:
arr = np.arange(24)
re_arr = np.reshape(arr,(12,2))
print(arr)
print(re_arr)
print(re_arr.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
2


In [40]:
arr = np.arange(24).reshape(2,3,4)
print(arr)
print(arr.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
3


In [42]:
new_data = np.swapaxes(arr,0,2)
print(new_data)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


In [44]:
a1 = np.array([[12,13,14],[15,16,17],[18,19,20]])
a2 = np.array([[2,3,4],[5,6,7]])
concat = np.concatenate((a1,a2))
print(concat)

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [ 2  3  4]
 [ 5  6  7]]
