In [1]:
import numpy as np

In [8]:
#arange(start,stop,step,datatype) its abut genrating array
data = np.arange(0,10,2,dtype= int)
print(data)

[0 2 4 6 8]


In [10]:
data = np.arange(0.5,5.5,1.0,dtype= float)
print(data)

[0.5 1.5 2.5 3.5 4.5]


In [14]:
data = np.arange(10,2,-2,dtype= int)
print(data)

[10  8  6  4]


In [17]:
#np.linspace(start,stop,num=50,endpoint=true,retstep=false,dtype 50 is default number set endpt & restep is also default)
data , step= np.linspace(0,10,5,endpoint = True,retstep = True)
print(data)
print("step size :",step)

[ 0.   2.5  5.   7.5 10. ]
step size : 2.5


In [18]:
data , step= np.linspace(0,10,5,endpoint = False,retstep = True)
print(data)
print("step size :",step)

[0. 2. 4. 6. 8.]
step size : 2.0


In [19]:
data = np.logspace(1,3,4,base =10)
print(data)


[  10.           46.41588834  215.443469   1000.        ]
